//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace taskodc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class courseContent
    {
        public int id { get; set; }
        public string content { get; set; }
        public Nullable<int> idCourse { get; set; }
        public int Quiz { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
