//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace taskodc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public int idSkill { get; set; }
        public string nameSkill { get; set; }
        public int degreeQuiz { get; set; }
        public int idCourseSkill { get; set; }
        public int idUserSkill { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual User User { get; set; }
    }
}
