//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace taskodc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userCourse
    {
        public int idUserCourse { get; set; }
        public int idUser { get; set; }
        public int idCourses { get; set; }
        public int Quiz { get; set; }
        public int yourProgress { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual User User { get; set; }
    }
}
